#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: 'abhinav1#'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: transaction-using-hibernate-client
  server:
    port: 0
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true